spring:
  messages:
    basename: i18n/messages

  datasource:
    url: jdbc:h2:mem:technical_test
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

